
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.transaction.xa.XAResource;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PRABH
 */
public class ClientJFrame extends JFrame
{
ViewFrame.TableModel tm;
    Client ct;
    SignUp signupform;
    TableModel f_tm=new TableModel();
    LogInJFrame loginform;
    ArrayList<user> u_al = new ArrayList<>();
    ArrayList<String> f_al=new ArrayList<>();
    SearchJFrame serform;
    ViewFrame viewform;
    int index=-1;
    /**
     * Creates new form ClientJFrame
     */
    public ClientJFrame()
    {
        initComponents();
        setSize(300, 300);
        setVisible(true);
        jTable1.setModel(f_tm);
         jScrollPane1.setVisible(false);
         jButton3.setVisible(false);
         jButton4.setVisible(false);
         jButton5.setVisible(false);
         
             TableModel tm;
              String name;
        ct = new Client();
        Thread t = new Thread(ct);
        t.start();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenu1 = new javax.swing.JMenu();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(null);

        jButton2.setText("SignUp");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 50, 170, 23);

        jButton1.setText("LogIn");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 100, 180, 23);

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 150, 180, 30);

        jButton4.setText("View Pending requests");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 210, 180, 30);

        jButton5.setText("View Online Friends");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(30, 263, 170, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(232, 40, 250, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        signupform = new SignUp();
        signupform.setVisible(true);
        jButton2.setEnabled(false);
//        signupform.setVisible(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginform = new LogInJFrame();
        loginform.setVisible(true);
        jButton1.setEnabled(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        serform = new SearchJFrame();
        serform.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed

        viewform = new ViewFrame();
        viewform.setVisible(true);
        try
        {
            ct.dos.writeBytes("ViewPendingRequests\r\n");
        } catch (Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
      try
        {
            ct.dos.writeBytes("ViewOnlineFriends\r\n");
        } catch (Exception e)
        {
            e.printStackTrace();
        }
      
    }//GEN-LAST:event_jButton5ActionPerformed
    public class Client implements Runnable
    {

        DataOutputStream dos = null;
        DataInputStream dis = null;

        public void run()
        {

            try
            {
                Socket sock = new Socket("127.0.0.1", 9000);
                dos = new DataOutputStream(sock.getOutputStream());

                dis = new DataInputStream(sock.getInputStream());
                String s = dis.readLine();
                System.out.println(" s: " + s);
                dos.writeBytes("Hello server....\r\n");
                while (true)
                {
                    s = dis.readLine();
                    if (s.equals("loginresponse"))
                    {
                        String response = dis.readLine();
                        System.out.println(" response " + response);
                        if (response.equals("alreadyexist"))
                        {
                            JOptionPane.showMessageDialog(signupform, "User already exist");
                        } else
                        {
                            JOptionPane.showMessageDialog(signupform, "sucessfully added");
                        }
                    } else if (s.equals("login"))
                    {
                        String response = dis.readLine();
                        System.out.println(" response " + response);
                        if (response.equals("login successfully"))
                        {
                            JOptionPane.showMessageDialog(loginform, "Login successfully");
                            loginform.dispose();
                            jButton3.setVisible(true);
                            jButton4.setVisible(true);
                            jButton5.setVisible(true);
                        } else
                        {
                            JOptionPane.showMessageDialog(loginform, "Login failed");
                        }
                    } else if (s.equals("searchresponse"))
                    {
                        u_al.clear();
                        // String searchstring=dis.readLine();
                        System.out.println("Search successfully");
                           
                        while (true)
                        {
                            String name = dis.readLine();
                            System.out.println(" name " + name);
                            if (name.equals("end"))
                            {
                                break;
                            }
                            String gender = dis.readLine();
                            String user = dis.readLine();
                            u_al.add(new user(name, gender, user));
                            serform.tm.fireTableDataChanged();
                        }

                    } else if (s.equals("ViewPendingRequests"))
                    {
                        JOptionPane.showMessageDialog(serform, dis.readLine());
                              
                            
                    } else if (s.equals("ViewPendingRequestsResponce"))
                    {
                        u_al.clear();
                        // String searchstring=dis.readLine();
                        System.out.println("View successfully");

                        while (true)
                        {
                            String name = dis.readLine();
                            System.out.println(" name " + name);
                            if (name.equals("end"))
                            {
                                break;
                            }
                            String gender = dis.readLine();
                            String user = dis.readLine();
                            u_al.add(new user(name, gender, user));
                            tm.fireTableDataChanged();
                        }

                    }
                    else if(s.equals("Friend request accepted"))
                    {
                        JOptionPane.showMessageDialog(rootPane, "Friend Request accepted");
                        u_al.remove(index);
                        tm.fireTableDataChanged();
                    }
              else if(s.equals("Request Rejected"))
                    {
                        JOptionPane.showMessageDialog(rootPane, "Request Rejected");
                        u_al.remove(index);
                        tm.fireTableDataChanged();
                    }
              else if(s.equals("Review list")){
                  int size=dis.readInt();
                  jScrollPane1.setVisible(true);
                  for(int i=0;i<size;i++)
                  {
                      String name=dis.readLine();
                      System.out.println(name);
                      f_al.add(name);
                      f_tm.fireTableDataChanged();
                  }
              }
                }
            } catch (Exception ex)
            {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);

            }
        }

//    public static void main(String[] args) throws IOException {
//      new Client();
//    }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ClientJFrame().setVisible(true);
            }
        });
    }

    /*
     * To change this license header, choose License Headers in Project Properties.
     * To change this template file, choose Tools | Templates
     * and open the template in the editor.
     */
    /**
     *
     * @author PRABH
     */
    public class SignUp extends javax.swing.JFrame
    {

        /**
         * Creates new form SignUp
         */
        String gender = "";

        public SignUp()
        {
            initComponents();
            setSize(350, 525);
            setVisible(true);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents()
        {

            jTextField7 = new javax.swing.JTextField();
            buttonGroup1 = new javax.swing.ButtonGroup();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jTextField1 = new javax.swing.JTextField();
            jTextField2 = new javax.swing.JTextField();
            jTextField3 = new javax.swing.JTextField();
            jTextField4 = new javax.swing.JTextField();
            jTextField5 = new javax.swing.JTextField();
            jTextField6 = new javax.swing.JTextField();
            jRadioButton1 = new javax.swing.JRadioButton();
            jRadioButton2 = new javax.swing.JRadioButton();
            jLabel8 = new javax.swing.JLabel();
            jTextField8 = new javax.swing.JTextField();
            jLabel9 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();

            jTextField7.setText("jTextField1");

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(null);

            jLabel1.setText("Create Account");
            getContentPane().add(jLabel1);
            jLabel1.setBounds(90, 10, 110, 29);

            jLabel2.setText(" Confirm Password");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(10, 400, 110, 20);

            jLabel3.setText("UserName");
            getContentPane().add(jLabel3);
            jLabel3.setBounds(20, 60, 70, 20);

            jLabel4.setText("Name");
            getContentPane().add(jLabel4);
            jLabel4.setBounds(20, 110, 40, 20);

            jLabel5.setText("Email");
            getContentPane().add(jLabel5);
            jLabel5.setBounds(20, 160, 50, 20);

            jLabel6.setText("Phone no:");
            getContentPane().add(jLabel6);
            jLabel6.setBounds(20, 210, 60, 20);

            jLabel7.setText("DOB");
            getContentPane().add(jLabel7);
            jLabel7.setBounds(20, 300, 60, 20);

            jTextField1.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jTextField1ActionPerformed(evt);
                }
            });
            getContentPane().add(jTextField1);
            jTextField1.setBounds(150, 290, 120, 30);

            jTextField2.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jTextField2ActionPerformed(evt);
                }
            });
            getContentPane().add(jTextField2);
            jTextField2.setBounds(150, 60, 120, 30);

            jTextField3.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jTextField3ActionPerformed(evt);
                }
            });
            getContentPane().add(jTextField3);
            jTextField3.setBounds(150, 110, 120, 30);
            getContentPane().add(jTextField4);
            jTextField4.setBounds(150, 160, 120, 30);

            jTextField5.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jTextField5ActionPerformed(evt);
                }
            });
            getContentPane().add(jTextField5);
            jTextField5.setBounds(150, 390, 120, 30);
            getContentPane().add(jTextField6);
            jTextField6.setBounds(150, 210, 120, 30);

            buttonGroup1.add(jRadioButton1);
            jRadioButton1.setText("Female");
            jRadioButton1.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jRadioButton1ActionPerformed(evt);
                }
            });
            getContentPane().add(jRadioButton1);
            jRadioButton1.setBounds(200, 250, 80, 30);

            buttonGroup1.add(jRadioButton2);
            jRadioButton2.setText("Male");
            jRadioButton2.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jRadioButton2ActionPerformed(evt);
                }
            });
            getContentPane().add(jRadioButton2);
            jRadioButton2.setBounds(150, 250, 50, 30);

            jLabel8.setText("Gender");
            getContentPane().add(jLabel8);
            jLabel8.setBounds(20, 260, 60, 20);

            jTextField8.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jTextField8ActionPerformed(evt);
                }
            });
            getContentPane().add(jTextField8);
            jTextField8.setBounds(150, 340, 120, 30);

            jLabel9.setText("Password");
            getContentPane().add(jLabel9);
            jLabel9.setBounds(20, 350, 60, 20);

            jButton1.setText("Signup");
            jButton1.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButton1ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton1);
            jButton1.setBounds(80, 443, 70, 30);

            pack();
        }// </editor-fold>                        

        private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt)
        {
            // TODO add your handling code here:
        }

        private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)
        {
            // TODO add your handling code here:
            gender = "Female";
        }

        private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt)
        {
        // TODO add your handling code here:

        }

        private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt)
        {
            // TODO add your handling code here:
        }

        private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt)
        {
            // TODO add your handling code here:
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
        {

            {
                String username = jTextField2.getText();
                String Name = jTextField3.getText();
                String Email = jTextField4.getText();
                String Phone_no = jTextField6.getText();
                String DOB = jTextField1.getText();
                String Password = jTextField8.getText();
                String confpassword = jTextField5.getText();

                if (username.equals("") || Name.equals("") || Email.equals("") || Phone_no.equals("") || gender.equals("") || DOB.equals("") || Password.equals("") || confpassword.equals(""))
                {
                    JOptionPane.showMessageDialog(this, "Fill Out field first");
                } else if (!Password.equals(confpassword))
                {
                    JOptionPane.showMessageDialog(this, "Password doesn't match ");
                } else
                {
                    try
                    {
                        ct.dos.writeBytes("signuprequest\r\n");
                        ct.dos.writeBytes(username + "\r\n");
                        ct.dos.writeBytes(Name + "\r\n");
                        ct.dos.writeBytes(Email + "\r\n");
                        ct.dos.writeBytes(Phone_no + "\r\n");
                        ct.dos.writeBytes(gender + "\r\n");
                        ct.dos.writeBytes(DOB + "\r\n");
                        ct.dos.writeBytes(Password + "\r\n");
                        ct.dos.writeBytes(confpassword + "\r\n");
                    } catch (Exception e)
                    {
                        e.printStackTrace();
                    }
                }
            }

        }

        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)
        {
            // TODO add your handling code here:
        }

        private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt)
        {
            gender = "Male";
        }

        /**
         * @param args the command line arguments
         */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SignUp().setVisible(true);
//            }
//        });
//    }
        // Variables declaration - do not modify                     
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JRadioButton jRadioButton1;
        private javax.swing.JRadioButton jRadioButton2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JTextField jTextField6;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JTextField jTextField8;
    // End of variables declaration                       
    }

    public class LogInJFrame extends javax.swing.JFrame
    {

        /**
         * Creates new form LogInJFrame
         */
        public LogInJFrame()
        {
            initComponents();
            setSize(300, 200);
            setVisible(true);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents()
        {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jTextField1 = new javax.swing.JTextField();
            jPasswordField1 = new javax.swing.JPasswordField();
            jButton1 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(153, 255, 255));
            getContentPane().setLayout(null);

            jLabel1.setText("UserName");
            getContentPane().add(jLabel1);
            jLabel1.setBounds(10, 40, 80, 20);

            jLabel2.setText("Password");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(10, 80, 80, 20);

            jTextField1.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jTextField1ActionPerformed(evt);
                }
            });
            getContentPane().add(jTextField1);
            jTextField1.setBounds(100, 40, 120, 25);
            getContentPane().add(jPasswordField1);
            jPasswordField1.setBounds(100, 80, 120, 25);

            jButton1.setText("LogIn");
            jButton1.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButton1ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton1);
            jButton1.setBounds(60, 120, 73, 23);

            pack();
        }// </editor-fold>                        

        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)
        {
            // TODO add your handling code here:
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
        {
            // TODO add your handling code here:
            String username = jTextField1.getText();
            String password = jPasswordField1.getText();

            if (username.equals("") || password.equals(""))
            {
                JOptionPane.showMessageDialog(this, "Fill fields first");
            } else
            {
                try
                {
                    ct.dos.writeBytes("login\r\n");
                    ct.dos.writeBytes(username + "\r\n");
                    ct.dos.writeBytes(password + "\r\n");
                } catch (IOException ex)
                {
                    Logger.getLogger(ClientJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
//         jButton3.setVisible(true);
//        jButton4.setVisible(true);        
        }
        /**
         * @param args the command line arguments
         */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LogInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LogInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LogInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LogInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LogInJFrame().setVisible(true);
//            }
//        });
//    }

        // Variables declaration - do not modify                     
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPasswordField jPasswordField1;
        private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
    }

    public class SearchJFrame extends javax.swing.JFrame
    {

        TableModel1 tm;

        /**
         * Creates new form SearchJFrame
         */
        public SearchJFrame()
        {
            initComponents();
            setSize(400, 200);
            setVisible(true);
            tm = new TableModel1();
            jTable1.setModel(tm);
            jButton3.setVisible(false);
        }

        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents()
        {

            jTextField1 = new javax.swing.JTextField();
            jButton1 = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTable1 = new javax.swing.JTable();
            jButton2 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(null);
            getContentPane().add(jTextField1);
            jTextField1.setBounds(10, 33, 170, 28);

            jButton1.setText("Search");
            jButton1.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButton1ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton1);
            jButton1.setBounds(200, 33, 110, 30);

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]
                    {
                        {
                            null, null, null, null
                        },
                        {
                            null, null, null, null
                        },
                        {
                            null, null, null, null
                        },
                        {
                            null, null, null, null
                        }
                    },
                    new String[]
                    {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
            ));
            jScrollPane1.setViewportView(jTable1);

            getContentPane().add(jScrollPane1);
            jScrollPane1.setBounds(30, 80, 310, 170);

            jButton2.setText("Send Friend request");
            jButton2.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButton2ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton2);
            jButton2.setBounds(40, 290, 180, 40);

            pack();
        }// </editor-fold>        

        class TableModel1 extends AbstractTableModel
        {

            @Override
            public int getRowCount()
            {

                return u_al.size();
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int getColumnCount()
            {
                return 2;
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex)
            {
                if (columnIndex == 1)
                {
                    return u_al.get(rowIndex).gender;
                } else
                {
                    return u_al.get(rowIndex).name;
                }

//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
        {
            // TODO add your handling code here:
            String search = jTextField1.getText();
            if (search.equals(""))
            {
                JOptionPane.showMessageDialog(this, "Fill fields first");
            } else
            {
                try
                {
                    ct.dos.writeBytes("searchrequest\r\n");
                    ct.dos.writeBytes(search + "\r\n");

                } catch (Exception ex)
                {
                    ex.printStackTrace();
                }

            }

        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
        {
            int r = jTable1.getSelectedRow();
            if (r == -1)
            {
                JOptionPane.showMessageDialog(this, "Select row first");
            } else
            {
                try
                {
                    ct.dos.writeBytes("SendFriendRequest\r\n");
                    ct.dos.writeBytes(u_al.get(r).username + "\r\n");
                } catch (IOException ex)
                {
                    Logger.getLogger(ClientJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        // End of variables declaration                   
    }

    class user
    {

        String name, gender, username;

        user(String name, String gender, String username)
        {
            this.username = username;
            this.name = name;
            this.gender = gender;
        }
    }

    public class ViewFrame extends javax.swing.JFrame
    {

        

        public ViewFrame()
        {
            initComponents();
            tm = new TableModel();
            jTable1.setModel(tm);
            setVisible(true);
              jButton4.setVisible(false);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents()
        {

            jScrollPane1 = new javax.swing.JScrollPane();
            jTable1 = new javax.swing.JTable();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(null);

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]
                    {
                        {
                            null, null, null, null
                        },
                        {
                            null, null, null, null
                        },
                        {
                            null, null, null, null
                        },
                        {
                            null, null, null, null
                        }
                    },
                    new String[]
                    {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
            ));
            jScrollPane1.setViewportView(jTable1);

            getContentPane().add(jScrollPane1);
            jScrollPane1.setBounds(80, 10, 375, 275);

            jButton1.setText("Accept Request");
            getContentPane().add(jButton1);
            jButton1.setBounds(40, 343, 160, 30);
            jButton1.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButton1ActionPerformed(evt);
                }
            });
            jButton2.setText("Reject Request");
            jButton2.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    jButton2ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton2);
            jButton2.setBounds(300, 340, 160, 30);

            pack();
        }// </editor-fold> 

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
        {
            int r = jTable1.getSelectedRow();
            if (r == -1)
            {
                JOptionPane.showMessageDialog(this, "Select Row First");
            } else
            {
                try
                {
                    index = r;
                    ct.dos.writeBytes("AcceptRequest\r\n");
                    ct.dos.writeBytes(u_al.get(r).username + "\r\n");
                } catch (Exception e)
                {
                    e.printStackTrace();
                }
            }
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
        {
              int r = jTable1.getSelectedRow();
            if (r == -1)
            {
                JOptionPane.showMessageDialog(this, "Select Row First");
            } else
            {
                index=r;
                  try
                  {
                      ct.dos.writeBytes("RejectRequest\r\n");
                      ct.dos.writeBytes(u_al.get(r).username + "\r\n");
                  } catch (Exception ex)
                  {
                      Logger.getLogger(ClientJFrame.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  
            }
        }
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Nimbus".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                new ViewFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify                     
        // End of variables declaration 
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;

        class TableModel extends AbstractTableModel
        {

            @Override
            public int getRowCount()
            {

                return u_al.size();
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int getColumnCount()
            {
                return 2;
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex)
            {
                if (columnIndex == 1)
                {
                    return u_al.get(rowIndex).gender;
                } else
                {
                    return u_al.get(rowIndex).name;
                }

//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        }
    }
    
 class TableModel extends AbstractTableModel
        {

            @Override
            public int getRowCount()
            {

                return f_al.size();
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
  
            @Override
            public int getColumnCount()
            {
                return 1;
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex)
            {
                if (columnIndex == 0)
                {
                    return f_al.get(rowIndex);
                } 
                return null;
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
