import java.awt.Color;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GSB
 */
public class downloadpanel extends javax.swing.JPanel
{

    /**
     * Creates new form downloadpanel
     */
    public downloadpanel()
    {
        initComponents();
        setSize(170,100);
        setVisible(true);
        setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jProgressBar1 = new javax.swing.JProgressBar();
        lbfile = new javax.swing.JLabel();
        lbuser = new javax.swing.JLabel();

        setLayout(null);

        jProgressBar1.setStringPainted(true);
        add(jProgressBar1);
        jProgressBar1.setBounds(10, 10, 146, 17);
        add(lbfile);
        lbfile.setBounds(10, 30, 150, 20);
        add(lbuser);
        lbuser.setBounds(10, 60, 150, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JLabel lbfile;
    public javax.swing.JLabel lbuser;
    // End of variables declaration//GEN-END:variables
}
